version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /var/lib/pgadmin/data:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  app:
    links: 
    - postgres:postgres
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    ports:
    - "3000:3000"
    volumes:
    - ./app:/app
    networks:
    - postgres
  
 
networks:
  postgres:
    driver: bridge