version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /mnt/nfs/homes/mbouzaie/sgoinfre/postgresql/data:/mnt/nfs/homes/mbouzaie/sgoinfre/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /mnt/nfs/homes/mbouzaie/sgoinfre/pgadmin/data:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge
    driver: bridge